// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO
    refresh_tokens (
        token,
        expires_at,
        user_id,
        created_at,
        updated_at
    )
VALUES
    ($1, $2, $3, NOW(), NOW())
`

type CreateRefreshTokenParams struct {
	Token     string
	ExpiresAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.Token, arg.ExpiresAt, arg.UserID)
	return err
}

const getUserFromValidRefreshToken = `-- name: GetUserFromValidRefreshToken :one
SELECT
    user_id
FROM
    refresh_tokens
WHERE
    token = $1
    AND expires_at > NOW()
    AND revoked_at IS NULL
ORDER BY
    created_at desc
`

func (q *Queries) GetUserFromValidRefreshToken(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserFromValidRefreshToken, token)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET
    updated_at = NOW(),
    revoked_at = NOW()
WHERE
    token = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}
